server:
  port: 8080

spring:
  application:
    name: simple-examine

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: ${jdbc.mysql.username}
    password: ${jdbc.mysql.password}
    driver-class-name: ${jdbc.mysql.driver}
    url: ${jdbc.mysql.url}
    druid:
      #配置监控统计拦截的 filters,去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat, wall
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # StatViewServlet配置。（因为暴露的监控信息比较敏感，支持密码加密和访问ip限定）
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 用的shiro，在登录时需要把用户名存入session，找不到session
      #        login-username: admin
      #        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
      wall:
        config:
          multi-statement-allow: true

  http:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

#mybatis plus配置
mybatis-plus:
  type-aliases-package: com.cdtu.simpleexamine.pojo.dbo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true           # 开启驼峰转换
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 35729
  restart:
    enabled: true #是否支持热部署

#配置staff头像地址
system:
  staff:
    avatar:
      location: /static/staffLocation
  admin:
    avatar:
      location: /static/adminLocation

#日志配置
logging:
  level:
    root: info
#  path:                 #配置日志输出位置
